clientes/urls.py
from django.urls import path
from . import views

app_name = 'clientes'

urlpatterns = [
    path('registrar/', views.registrar_cliente, name='registrar_cliente'),
    path('login/', views.logar_cliente, name='login_cliente'),
    path('logout/', views.deslogar_cliente, name='logout_cliente'),
    path('salvar_endereco/', views.salvar_endereco, name='salvar_endereco'),
    path('excluir_endereco/<str:id>/', views.excluir_endereco, name='excluir_endereco'),
    path('atualizar_dados/', views.atualizar_dados, name='atualizar_dados')
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'


urlpatterns = [
    path('', views.graph, name="graph"),
    # path('retorna_total_vendido', views.retorna_total_vendido, name="retorna_total_vendido"),
    path('relatorio_faturamento', views.relatorio_faturamento, name="relatorio_faturamento"),
    path('relatorio_produtos', views.relatorio_produtos, name="relatorio_produtos"),
    path('relatorio_vendas', views.relatorio_vendas, name="relatorio_vendas"),
    path('relatorio_clientes', views.relatorio_clientes, name="relatorio_clientes"),
    path('relatorio_pizza', views.relatorio_pizza, name="relatorio_pizza"),
    
    
]

menu/urls.py
from django.urls import path
from . import views
app_name = 'menu'

urlpatterns = [
    path('', views.index, name='index'),
    path('menu/', views.index, name='index_alt'),
    path('buscar/', views.buscar, name='buscar'),
    path('adicionar_ao_carrinho/<str:id>/', views.adicionar_ao_carrinho, name='adicionar_ao_carrinho'),
    path('remover_do_carrinho/<str:id>/', views.remover_do_carrinho, name='remover_do_carrinho'),
    path('excluir_do_carrinho/<str:id>/', views.excluir_do_carrinho, name='excluir_do_carrinho'),
]

pedidos/urls.py
from django.urls import path
from . import views
app_name = 'pedidos'

urlpatterns = [
    path('finalizar_pedido/', views.finalizar_pedido, name='finalizar_pedido'),
    path('historico_de_pedidos/', views.historico_de_pedidos, name='historico_de_pedidos'),
]

pizzaria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menu.urls')),
    path('cliente/', include('clientes.urls')),
    path('pedido/', include('pedidos.urls')),
    path('dashboard/', include('dashboard.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

templates/partials/_cartoffcanvas.html
<div class="offcanvas offcanvas-end" tabindex="-1" id="carrinhoOffcanvas" aria-labelledby="carrinhoOffcanvasLabel">
  <div class="offcanvas-header">
      <h5 class="offcanvas-title display-6" id="carrinhoOffcanvasLabel">Meu Carrinho</h5>
      <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
      {% include "menu/carrinho.html" %}
  </div>
</div>

templates/partials/_header.html
<header>
  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #333333">
    <div class="container">
      <a class="navbar-brand" href="{% url 'menu:index' %}">
        <i class="fas fa-pizza-slice fa-lg me-2"></i>Pizza Express
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ms-auto">
          <a class="nav-link active" aria-current="page" href="{% url 'menu:index' %}">
            <i class="fas fa-book-open me-1"></i>Cardápio
          </a>
          <div class="nav-item dropdown">
            <a class="nav-link active dropdown-toggle" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="fas fa-user me-1"></i>{{ user.first_name }}
            </a>
            <ul class="dropdown-menu" aria-labelledby="userDropdown" style="font-size: 1em;">
              {% if user.is_authenticated %}
                <li><a class="dropdown-item" href="{% url "clientes:atualizar_dados" %}"><i class="fas fa-user-edit me-1"></i> Alterar Dados</a></li>
                <li><a class="dropdown-item" href="{% url 'pedidos:historico_de_pedidos' %}"><i class="fas fa-history me-1"></i> Histórico de Pedidos</a></li>
                {% if user.is_staff %}
                  <li><a class="dropdown-item" href="{% url 'dashboard:graph' %}"><i class="fas fa-chart-line"></i> Dashboard</a></li>
                {% endif %}
                <li><a class="dropdown-item" href="{% url 'clientes:logout_cliente' %}"><i class="fas fa-sign-out-alt me-1"></i> Sair</a></li>

              {% else %}
                <li><a class="dropdown-item" href="{% url 'clientes:registrar_cliente' %}"><i class="fas fa-user-plus me-1"></i> Criar Conta</a></li>
                <li><a class="dropdown-item" href="{% url 'clientes:login_cliente' %}"><i class="fas fa-sign-in-alt me-1"></i> Login</a></li>
              {% endif %}
            </ul>
          </div>
          {% if request.resolver_match.view_name == "menu:index" or qtd_item_carrinho %}
            <button class="nav-link active" data-bs-toggle="offcanvas" data-bs-target="#carrinhoOffcanvas" aria-controls="carrinhoOffcanvas">
              <i class="fas fa-shopping-cart me-1"></i>Carrinho
              <span id="qtd-item-carrinho" class="badge bg-light text-dark rounded-pill ms-1">{{ qtd_item_carrinho }}</span>
            </button>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>
</header>

templates/partials/_pagination.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if query %}&q={{ query }}{% endif %}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ num }}{% if query %}&q={{ query }}{% endif %}">{{ num }}</a></li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if query %}&q={{ query }}{% endif %}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% endif %}
    </ul>
</nav>
{% endif %}