menu/urls.py
from django.urls import path
from . import views
app_name = 'menu'

urlpatterns = [
    path('', views.index, name='index'),
    path('menu/', views.index, name='index_alt'),
    path('buscar/', views.buscar, name='buscar'),
    path('adicionar_ao_carrinho/<str:id>/', views.adicionar_ao_carrinho, name='adicionar_ao_carrinho'),
    path('remover_do_carrinho/<str:id>/', views.remover_do_carrinho, name='remover_do_carrinho'),
    path('excluir_do_carrinho/<str:id>/', views.excluir_do_carrinho, name='excluir_do_carrinho'),
]

pedidos/urls.py
from django.urls import path
from . import views
app_name = 'pedidos'

urlpatterns = [
    path('finalizar_pedido/', views.finalizar_pedido, name='finalizar_pedido'),
    path('historico_de_pedidos/', views.historico_de_pedidos, name='historico_de_pedidos'),
]

pizzaria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menu.urls')),
    path('cliente/', include('clientes.urls')),
    path('pedido/', include('pedidos.urls')),
    path('dashboard/', include('dashboard.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

menu/models.py
from django.db import models

# Create your models here.

class Produto(models.Model):
    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'
    
    nome = models.CharField(max_length=30)
    preco = models.DecimalField(max_digits=8, decimal_places=2)
    descricao = models.TextField()
    categoria = models.CharField(max_length=50, choices=[("Pizza", "Pizza"), ("Bebida", "Bebida")])

    def __str__(self):
        return self.nome

menu/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404, redirect
from django.contrib import messages
from menu.models import Produto
from pedidos.models import ItemCarrinho, Carrinho, Pedido
from clientes.models import CustomUser
from utils.functions import calcula_valor_total_carrinho
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.core.paginator import Paginator
from django.http import JsonResponse


@login_required(login_url='clientes:login_cliente')
def index(request):
    """
    Primeira tela do site.
    Exibe os itens do cardápio
    """
    produtos = Produto.objects.all().order_by('-categoria')
    paginator = Paginator(produtos, 7)  # 10 produtos por pagina
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    usuario = get_object_or_404(CustomUser, username=request.user)
    carrinho_vinculado = get_object_or_404(Carrinho, cliente=usuario)

    # Incorporacao da view carrinho_detalhado
    item_carrinho = ItemCarrinho.objects.filter(carrinho=carrinho_vinculado)
    subtotal = calcula_valor_total_carrinho(item_carrinho)

    qtd_itens_carrinho = ItemCarrinho.objects.filter(
        carrinho=carrinho_vinculado
    ).count()

    context = {
        'page_obj': page_obj,
        'carrinho': carrinho_vinculado,
        'qtd_item_carrinho': qtd_itens_carrinho,
        'item_carrinho': item_carrinho,
        'produtos': produtos,
        'subtotal': subtotal,
    }

    return render(request, 'menu/index.html', context)


@login_required(login_url='clientes:login_cliente')
def buscar(request):
    usuario = get_object_or_404(CustomUser, username=request.user)
    carrinho_vinculado = get_object_or_404(Carrinho, cliente=usuario)
    qtd_itens_carrinho = ItemCarrinho.objects.filter(
        carrinho=carrinho_vinculado
    ).count()

    query = request.GET.get("q", '').strip()
    if query == "":
        return redirect('menu:index')

    produtos = Produto.objects.filter(
        Q(nome__icontains=str(query))
        | Q(descricao__icontains=str(query))
        | Q(categoria__icontains=str(query))
    ).order_by('-nome')
    paginator = Paginator(produtos, 7)  # 10 produtos por pagina
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    item_carrinho = ItemCarrinho.objects.filter(carrinho=carrinho_vinculado)
    subtotal = calcula_valor_total_carrinho(item_carrinho)
    qtd_itens_carrinho = ItemCarrinho.objects.filter(
        carrinho=carrinho_vinculado
    ).count()

    context = {
        'page_obj': page_obj,
        'carrinho': carrinho_vinculado,
        'qtd_item_carrinho': qtd_itens_carrinho,
        'item_carrinho': item_carrinho,
        'produtos': produtos,
        'subtotal': subtotal,
        'query': query,
    }

    return render(request, 'menu/index.html', context)


@login_required(login_url='clientes:login_cliente')
def adicionar_ao_carrinho(request, id):
    usuario = get_object_or_404(CustomUser, username=request.user)

    produto = get_object_or_404(Produto, id=id)
    carrinho_vinculado = get_object_or_404(Carrinho, cliente=usuario)
    consulta = ItemCarrinho.objects.filter(produto=produto, carrinho=carrinho_vinculado)
    if consulta.exists():
        item = consulta.first()
        item.quantidade += 1
        item.save()

    else:
        item = ItemCarrinho.objects.create(
            produto=produto,
            carrinho=carrinho_vinculado,
            quantidade=1,
        )

    item_carrinho = ItemCarrinho.objects.filter(carrinho=carrinho_vinculado)
    subtotal = calcula_valor_total_carrinho(item_carrinho)
    qtd_itens_carrinho = ItemCarrinho.objects.filter(
        carrinho=carrinho_vinculado
    ).count()

    # messages.info(request, f'{produto.nome} adicionado ao carrinho')
    # return redirect(request.META.get('HTTP_REFERER', 'menu:index'))
    print(
        {
            "status": "success",
            "message": f"{produto.nome} adicionado ao carrinho",
            "quantidade": item.quantidade,
            "total": item.get_total(),
            "produto_id": item.produto.id,
            "total_price": subtotal,
        }
    )

    return JsonResponse(
        {
            "status": "success",
            "message": f"{produto.nome} adicionado ao carrinho",
            "quantidade": item.quantidade,
            "total": item.get_total(),
            "produto_id": item.produto.id,
            'qtd_item_carrinho': qtd_itens_carrinho,
            "total_price": subtotal,
            "produto_nome": produto.nome,
        }
    )


@login_required(login_url='clientes:login_cliente')
def remover_do_carrinho(request, id):
    usuario = get_object_or_404(CustomUser, username=request.user)

    produto = get_object_or_404(Produto, id=id)
    carrinho_vinculado = get_object_or_404(Carrinho, cliente=usuario)
    consulta = ItemCarrinho.objects.filter(
        produto=produto, carrinho=carrinho_vinculado
    ).first()
    if consulta:
        if consulta.quantidade > 1:
            consulta.quantidade -= 1
            consulta.save()
            quantidade_atual = consulta.quantidade
        elif consulta.quantidade == 1:
            consulta.delete()
            quantidade_atual = 0
    else:
        return JsonResponse(
            {"status": "error", "message": "Produto não encontrado no carrinho"},
            status=400,
        )

    # messages.warning(request, f'{produto.nome} removido do carrinho')
    # return redirect(request.META.get('HTTP_REFERER', 'menu:index'))
    item_carrinho = ItemCarrinho.objects.filter(carrinho=carrinho_vinculado)
    subtotal = calcula_valor_total_carrinho(item_carrinho)
    qtd_itens_carrinho = ItemCarrinho.objects.filter(
        carrinho=carrinho_vinculado
    ).count()

    print(
        {
            "status": "success",
            "message": f"{produto.nome} removido do carrinho",
            "quantidade": quantidade_atual,
            "total": consulta.get_total() if quantidade_atual > 0 else 0,
            "produto_id": produto.id,
            "total_price": subtotal,
        }
    )
    return JsonResponse(
        {
            "status": "success",
            "message": f"{produto.nome} removido do carrinho",
            "quantidade": quantidade_atual,
            "total": consulta.get_total() if quantidade_atual > 0 else 0,
            'qtd_item_carrinho': qtd_itens_carrinho,
            "produto_id": produto.id,
            "total_price": subtotal,
        }
    )


@login_required(login_url='clientes:login_cliente')
def excluir_do_carrinho(request, id):
    usuario = get_object_or_404(CustomUser, username=request.user)

    produto = get_object_or_404(Produto, id=id)
    carrinho_vinculado = get_object_or_404(Carrinho, cliente=usuario)
    consulta = ItemCarrinho.objects.filter(
        produto=produto, carrinho=carrinho_vinculado
    ).first()
    if consulta.quantidade >= 1:
        consulta.delete()

    qtd_itens_carrinho = ItemCarrinho.objects.filter(
        carrinho=carrinho_vinculado
    ).count()
    # messages.error(request, f'{produto.nome} excluído do carrinho')
    # return redirect(request.META.get('HTTP_REFERER', 'menu:index'))
    item_carrinho = ItemCarrinho.objects.filter(carrinho=carrinho_vinculado)
    subtotal = calcula_valor_total_carrinho(item_carrinho)

    return JsonResponse(
        {
            "status": "success",
            "message": f"{produto.nome} excluído do carrinho",
            "quantidade": 0,
            'qtd_item_carrinho': qtd_itens_carrinho,
            "produto_id": produto.id,
            "total_price": subtotal,
        }
    )

menu/templates/menu/carrinho.html
{% load static %}
    {% block content %}

    {% if item_carrinho %}
        {% include "carrinho_detalhado.html" %}
        <div id="finalizar-pedido" class="d-flex justify-content-between align-items-center mt-4 p-3 border rounded bg-light">
            <span id="valor-total" class="fs-4 fw-bold">Total: R$ {{ subtotal|floatformat:2|default:"0.00" }}</span>
            <a href="{% url 'pedidos:finalizar_pedido'  %}" class="btn btn-lg btn-danger ms-3">
                Finalizar pedido
                <i class="fas fa-shopping-cart ms-2"></i>
            </a>
        </div>    
    {% else %}
        <div id="finalizar-pedido" class="d-flex justify-content-between align-items-center mt-4 p-3 border rounded bg-light">
            <span class="fs-4 fw-bold">O carrinho está vazio!</span>
        </div>    
    {% endif %}
{% endblock content %}

menu/templates/menu/index.html
{% extends "base.html" %}
{% load static %}
    {% block title %}Cardápio{% endblock title %}

    {% block content %}
    <div class="d-flex justify-content-center">
        <h2 class="display-6">Cardápio</h2>
    </div>
    <div class="container">

        <div class="d-flex justify-content-center mt-3">
            <form action="{% url 'menu:buscar' %}" method="GET" class="w-50">
                <div class="input-group">
                    <input type="search" name="q" class="form-control p-3 fs-5" placeholder="Buscar produto" value="{{request.GET.q}}">
                    <button class="btn btn-primary" type="submit">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </form>
        </div>
    </div>
    {% if page_obj %}
        <div class="menu mt-4">
            {% for produto in page_obj %}
                <div class="menu-item d-flex justify-content-between align-items-center p-3 mb-3 border rounded">
                    <div class="menu-details">
                        <h2 class="mb-1">{{ produto.nome }}</h2>
                        <p class="text-muted">{{ produto.descricao }}</p>
                    </div>
                    <div class="menu-price d-flex align-items-center">
                        <span class="me-3 fs-4">R${{ produto.preco }}</span>
                        {% csrf_token %}
                        <a href="{% url 'menu:adicionar_ao_carrinho' produto.id %}" class="btn btn-success btn-ajax">
                            <i class="fas fa-cart-plus"></i>
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="alert alert-danger text-center fw-bold mt-5" role="alert">
            Nenhum produto encontrado.
        </div>
    {% endif %}

    <!-- Offcanvas for Carrinho -->
    {% include "partials/_cartoffcanvas.html" %}

{% endblock content %}