menu/urls.py
from django.urls import path
from . import views
app_name = 'menu'

urlpatterns = [
    path('', views.index, name='index'),
    path('menu/', views.index, name='index_alt'),
    path('buscar/', views.buscar, name='buscar'),
    path('adicionar_ao_carrinho/<str:id>/', views.adicionar_ao_carrinho, name='adicionar_ao_carrinho'),
    path('remover_do_carrinho/<str:id>/', views.remover_do_carrinho, name='remover_do_carrinho'),
    path('excluir_do_carrinho/<str:id>/', views.excluir_do_carrinho, name='excluir_do_carrinho'),
]

pizzaria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menu.urls')),
    path('cliente/', include('clientes.urls')),
    path('pedido/', include('pedidos.urls')),
    path('dashboard/', include('dashboard.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

templates/base.html
{% load static %}
{% load static %}
<!doctype html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'clientes/css/style.css' %}"> 

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <title> {% block title %}{% endblock %}</title>

  </head>
  
  <body>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/c97c47d39c.js" crossorigin="anonymous"></script>
    <script src="{% static 'pedidos/js/endereco.js' %}"></script>
    <script src="{% static 'pedidos/js/entrega.js' %}"></script>
    <script src="{% static 'menu/js/carrinho.js' %}"></script>
    <script src="{% static 'clientes/js/add_endereco.js' %}"></script>

    
    {% block bg %}
    <div class="background"></div>
    
    <style>
        .background {
            object-fit: cover; /* Garante que a imagem não distorça */
            position: fixed; 
            width: 100%;
            height: 100%;
            background: url("{% static 'clientes/img/11039274.jpg' %}") no-repeat center center/cover;
            {% comment %} filter: blur(10px); {% endcomment %}
            z-index: -1;
        }
    </style>
    {% endblock bg %}
    
    {% include "partials/_header.html" %}
    <main>
      {% if messages %}
        {% for message in messages %}
          <div class="alert {{ message.tags }}">
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      {% block content %}{% endblock content %}
      {% include "partials/_pagination.html" %}
      
    </main>
    {% block body %}
   
    {% endblock %}
  </body>
</html>

templates/carrinho_detalhado.html
<div id="item-carrinho" class="menu">
    {% csrf_token %}
    {% for item in item_carrinho %}
        <div id="menu-item-{{ item.produto.id }}-carrinho" class="menu-item d-flex justify-content-between align-items-center py-2 border-bottom">
            <div class="menu-details d-flex align-items-center flex-grow-1">
                <div class="quantity-controls d-flex align-items-center me-3">
                    <a href="{% url 'menu:remover_do_carrinho' item.produto.id %}" class="btn btn-danger btn-sm btn-ajax">
                        <i class="fas fa-minus"></i>
                    </a>
                    <span id="quantidade-{{ item.produto.id }}-carrinho" class="quantity mx-2">{{ item.quantidade }}</span>
                    <a href="{% url 'menu:adicionar_ao_carrinho' item.produto.id %}" class="btn btn-success btn-sm btn-ajax">
                        <i class="fas fa-plus"></i>
                    </a>
                </div>
                <span class="product-name flex-grow-1">{{ item.produto.nome }}</span>
                <span id="total-{{ item.produto.id }}-carrinho" class="product-total me-3">R$ {{ item.get_total|floatformat:2 }}</span>
            </div>
            <div class="remove-action">
                <a href="{% url 'menu:excluir_do_carrinho' item.produto.id %}" class="btn btn-outline-danger btn-ajax">
                    <i class="fas fa-trash"></i> 
                </a>
            </div>
        </div>
    {% endfor %}
</div>

templates/endereco_form.html
<div class="form-group">
  <label for="{{ address_form.rua.id_for_label}}" class="form-label">Rua</label>
  {{ address_form.rua }} {{ address_form.rua.errors }}

  <label for="{{ address_form.numero.id_for_label}}" class="form-label"
    >Número</label
  >
  {{ address_form.numero }} {{ address_form.numero.errors }}

  <label for="{{ address_form.bairro.id_for_label}}" class="form-label"
    >Bairro</label
  >
  {{ address_form.bairro }} {{ address_form.bairro.errors }}
</div>