dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'


urlpatterns = [
    path('', views.graph, name="graph"),
    # path('retorna_total_vendido', views.retorna_total_vendido, name="retorna_total_vendido"),
    path('relatorio_faturamento', views.relatorio_faturamento, name="relatorio_faturamento"),
    path('relatorio_produtos', views.relatorio_produtos, name="relatorio_produtos"),
    path('relatorio_vendas', views.relatorio_vendas, name="relatorio_vendas"),
    path('relatorio_clientes', views.relatorio_clientes, name="relatorio_clientes"),
    path('relatorio_pizza', views.relatorio_pizza, name="relatorio_pizza"),
    
    
]

menu/urls.py
from django.urls import path
from . import views
app_name = 'menu'

urlpatterns = [
    path('', views.index, name='index'),
    path('menu/', views.index, name='index_alt'),
    path('buscar/', views.buscar, name='buscar'),
    path('adicionar_ao_carrinho/<str:id>/', views.adicionar_ao_carrinho, name='adicionar_ao_carrinho'),
    path('remover_do_carrinho/<str:id>/', views.remover_do_carrinho, name='remover_do_carrinho'),
    path('excluir_do_carrinho/<str:id>/', views.excluir_do_carrinho, name='excluir_do_carrinho'),
]

pizzaria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menu.urls')),
    path('cliente/', include('clientes.urls')),
    path('pedido/', include('pedidos.urls')),
    path('dashboard/', include('dashboard.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

dashboard/models.py
from django.db import models

from typing import ClassVar
from django.db import models
import datetime
from menu.models import Produto


    

dashboard/views.py
from django.shortcuts import render, redirect
from django.http.response import HttpResponse, JsonResponse
from pedidos.models import ItemPedido
from menu.models import Produto
from datetime import datetime
from django.db.models import Count,Sum
from collections import Counter


def graph(request):
    if not request.user.is_superuser:
        return redirect(request.META.get('HTTP_REFERER', '/'))
    return render(request, 'graph.html')



# def retorna_total_vendido(request):
#     total = ItemPedido.objects.all().aggregate(Sum('total'))['total__sum']
#     if request.method == "GET":
#         return JsonResponse({'total': total})



def relatorio_faturamento(request):
    x = ItemPedido.objects.all()
    
    meses = ['jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez']
    data = []
    labels = []
    cont = 0
    mes = 0
    ano = datetime.now().year
    print(x)
    for m in range(0,12): 
        
        # if mes == 0:
        #     mes = 12
        #     ano -= 1
        
        y = sum([i.produto.preco * i.quantidade for i in x if i.data.month == m+1 and i.data.year == ano])
        
        labels.append(meses[m])
        data.append(y)
        cont += 1
        print(data, labels)
    data_json = {'data': data[::], 'labels': labels[::]}
     
    return JsonResponse(data_json)


def relatorio_vendas(request):
    x = ItemPedido.objects.all()
    print(x[0], 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
    meses = ['jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez']
    data = []
    labels = []
    cont = 0
    mes = 0
    ano = datetime.now().year
    for m in range(0,12): 
        
        # if mes == 0:
        #     mes = 12
        #     ano -= 1
        
        y = sum([i.quantidade for i in x if i.data.month == m+1 and i.data.year == ano])
        
        labels.append(meses[m])
        data.append(y)
        cont += 1
        print(data, labels)
    data_json = {'data': data[::], 'labels': labels[::]}
     
    return JsonResponse(data_json)

def relatorio_produtos(request):
    produtos = (ItemPedido.objects
          .select_related('menu__produto')  # Fazendo a junção com a tabela Produto
          .values('produto__categoria')  # Incluindo a categoria do produto
          .annotate(total=Count('id')))  
    print(produtos)
    label = []
    data = []
    for produto_unico in produtos:
        # quantidade_vendas = ItemPedido.objects.filter(produto=produto_unico).aggregate(Count('id'))
        # print(quantidade_vendas)
        if not produto_unico['total']:
            produto_unico['total'] = 0
        label.append(produto_unico['produto__categoria'])
        data.append(produto_unico['total'])

    x = list(zip(label, data))

    x.sort(key=lambda x: x[1], reverse=True)
    x = list(zip(*x))
    print(x)
    return JsonResponse({'labels': x[0][:], 'data': x[1][:]})


def relatorio_clientes(request):
    x = ItemPedido.objects.all().distinct('cliente_id')
    
    pedidos = ItemPedido.objects.all().order_by('cliente_id', 'data')


    pedidos_filtrados = {}
    ano_atual = datetime.now().year

    for pedido in pedidos:
        mes_ano = (pedido.cliente_id, pedido.data.year, pedido.data.month)  # Chave única para cliente/mês
        if mes_ano not in pedidos_filtrados:
            pedidos_filtrados[mes_ano] = pedido  # Mantemos apenas o primeiro encontrado

    # Convertendo para lista
    pedidos_filtrados = list(pedidos_filtrados.values())

    # Agora podemos calcular o total de quantidades por mês
    meses = ['jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez']
    data = []
    labels=[]
    for m in range(1, 13):  # De 1 a 12 para os meses
        total_quantidade = sum(p.quantidade for p in pedidos_filtrados if p.data.month == m and p.data.year == ano_atual)
        data.append(total_quantidade)
        labels.append(meses[m-1])
        
        print(data, labels)
    data_json2 = {'data': data[::], 'labels': labels[::]}
     
    return JsonResponse(data_json2)





def relatorio_pizza(request):
    mes_atual = datetime.now().month
    ano_atual = datetime.now().year
    print("to aquiiiiiiiiiiiiiiiiiiiii")
    # Filtra todos os itens do mês atual (sem usar Strftime)
    itens = ItemPedido.objects.select_related('produto').filter(produto__categoria='Pizza')

    # Filtra manualmente usando Python
    itens_filtrados = [item for item in itens if item.data.month == mes_atual and item.data.year == ano_atual]

    # Conta os produtos
    contador = Counter()
    for item in itens_filtrados:
        contador[item.produto.nome] += 1
    print("to aquiiiiiiiiiiiiiiiiiiiii")
    # Pega os 5 mais vendidos
    mais_vendidos = contador.most_common(5)
    labels = [nome for nome, _ in mais_vendidos]
    data = [quantidade for _, quantidade in mais_vendidos]
    print(labels,data)
    return JsonResponse({'labels': labels, 'data': data})
    #return JsonResponse({'labels': x[0][:], 'data': x[1][:]})

dashboard/templates/graph.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Dashboard {% endblock %}



{% block 'head' %}

    

{% endblock%}

{% block bg %}
    <div class="background"></div>

    <style>
        .background {
            position: fixed; /* Mantém o fundo fixo na tela */
            top: 0;
            left: 0;
            width: 100vw; /* 100% da largura da tela */
            height: 100vh; /* 100% da altura da tela */
            background-color: rgb(240, 235, 235) !important;
            filter: blur(10px); 
            z-index: -1;
        }
    </style>
{% endblock bg %}
{% block body %}
<div class="d-flex">
    <button id="exportarPDF" class="btn btn-secondary btn-lg">
    <i class="fas fa-file-pdf"></i>
    Exportar para PDF
    </button>
</div>


<div class="container" id="all-graphs">
    <br>
    {% comment %} <div class="row">

        <div  class="col-md informacoes_basicas">
            
            <h1> <svg class="icone" xmlns="http://www.w3.org/2000/svg"  fill="currentColor" class="bi bi-calendar-check" viewBox="0 0 16 16">
                <path d="M10.854 7.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7.5 9.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
                <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z"/>
            </svg>&nbspR$<span id="faturamento_total"></span></h1> 
            
        </div>

        <div class="col-md informacoes_basicas">
            <svg style="color: #69BDCB;" class="icone" xmlns="http://www.w3.org/2000/svg"  fill="currentColor" class="bi bi-cart-plus" viewBox="0 0 16 16">
                <path d="M9 5.5a.5.5 0 0 0-1 0V7H6.5a.5.5 0 0 0 0 1H8v1.5a.5.5 0 0 0 1 0V8h1.5a.5.5 0 0 0 0-1H9V5.5z"/>
                <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zm3.915 10L3.102 4h10.796l-1.313 7h-8.17zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
              </svg> <h1></h1> 
        </div>

        <div class="col-md informacoes_basicas">
            <svg  class="icone" xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-cash-coin" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M11 15a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm5-4a5 5 0 1 1-10 0 5 5 0 0 1 10 0z"/>
                <path d="M9.438 11.944c.047.596.518 1.06 1.363 1.116v.44h.375v-.443c.875-.061 1.386-.529 1.386-1.207 0-.618-.39-.936-1.09-1.1l-.296-.07v-1.2c.376.043.614.248.671.532h.658c-.047-.575-.54-1.024-1.329-1.073V8.5h-.375v.45c-.747.073-1.255.522-1.255 1.158 0 .562.378.92 1.007 1.066l.248.061v1.272c-.384-.058-.639-.27-.696-.563h-.668zm1.36-1.354c-.369-.085-.569-.26-.569-.522 0-.294.216-.514.572-.578v1.1h-.003zm.432.746c.449.104.655.272.655.569 0 .339-.257.571-.709.614v-1.195l.054.012z"/>
                <path d="M1 0a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h4.083c.058-.344.145-.678.258-1H3a2 2 0 0 0-2-2V3a2 2 0 0 0 2-2h10a2 2 0 0 0 2 2v3.528c.38.34.717.728 1 1.154V1a1 1 0 0 0-1-1H1z"/>
                <path d="M9.998 5.083 10 5a2 2 0 1 0-3.132 1.65 5.982 5.982 0 0 1 3.13-1.567z"/>
              </svg> <h1></h1> 
        </div>
       
    </div> {% endcomment %}


    <div class="row">
        
        <div class="col-md" >
            <br>

            <h1>Faturamento mensal:</h1>
            <canvas id="faturamento_mensal" width="250" height="200"></canvas>
        </div>
        
        <div class="col-md">
            <br>
            <h1>Vendas mensais:</h1>
            <canvas id="quantidade_de_vendas_mensal" width="250" height="200"></canvas>
        </div>

    </div>
    <br><br><br><br><br><br>
    <div class="row">
        
        <div class="col-md">
            <br>

            <h1>Produtos mais vendidos:</h1>
            <canvas id="produtos_mais_vendidos" width="10" height="50"></canvas>
        </div>
        <div class="col-md">
            <br>

            <h1>Clientes mensais distintos:</h1>
            <canvas id="clientes_mensal" width="250" height="250"> </canvas>
        </div>
        <div class="col-md">
            <br>

            <h1>Sabores mais pedidos:</h1>
            <canvas id="pizzas_vendidas" width="250" height="250"> </canvas>
        </div>
        
        
      

    </div>


</div>
<br>
<footer class="container">
    <br>
    
    <br>

  </footer>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="{% static 'dashboard/js/graph.js' %}"></script>
<script src="{% static 'dashboard/js/exportpdf.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"></script>


<script>
    window.onload = function(e){
    
    renderiza_faturamento_mensal('{% url "dashboard:relatorio_faturamento" %}')
    renderiza_vendas_mensal('{% url "dashboard:relatorio_vendas" %}')
    renderiza_produtos_mais_vendidos('{% url "dashboard:relatorio_produtos" %}')
    renderiza_clientes_mensal('{% url "dashboard:relatorio_clientes" %}')
    renderiza_pizza('{% url "dashboard:relatorio_pizza" %}')



}
</script>
{% endblock %}